  controller_manager_ns: ''
  controller_list:
    - name: pigot/group_arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - arm_rot_1
        - arm_rot_2
        - arm_rot_3
        - arm_rot_4
        - arm_rot_5
        - arm_rot_6
    - name: pigot/group_gripper_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - finger_joint1
        - finger_joint2